mujoco_ros_control/pid_gains:
  ra_shoulder_pan_joint: {p: 3000.0, i: 0.0, d: 300.0}
  ra_shoulder_lift_joint: {p: 12000.0, i: 100.0, d: 800.0}
  ra_elbow_joint: {p: 8000.0, i: 0.0, d: 30.0}
  ra_wrist_1_joint: {p: 2000.0, i: 0.0, d: 0.0}
  ra_wrist_2_joint: {p: 1900.0, i: 0.0, d: 0.0}
  ra_wrist_3_joint: {p: 400.0, i: 0.0, d: 0.0}
